### ISSUE TITLE
#5 -Footer Links

### ISSUE THREAD

**Issue by rakshitmaini** [batrasudhanshu/KidStation#5]
1. A lot of **footer links are not working**.
2. **Github** and **Linkedin** links should **open in new tab**.
3. Add **website intro/ abou**t in footer.
4. contact, track order and other links are also not working.

**Comment by batrasudhanshu** [comment]
**Quick Update on this issue** 

- Footer links are updated 👍 

- GitHub and LinkedIn links will open in new tab 👍 

- Website Intro/about is at pending state 👎 

- Contact, Track Order, Shipping, Return, Terms of Use links are now working 👍 
[Footer.js](https://github.com/batrasudhanshu/KidStation/blob/master/src/ui_components/Footer.js)

**Comment by rakshitmaini** [comment]
Website intro can be handled in other issue. Closing this one as well.
