### ISSUE TITLE
Folder delete from firebase storage

### ISSUE THREAD

**Issue by batrasudhanshu** [batrasudhanshu/KidStation#9]
While deleting the product , folder assigned to that product still exists in storage.

**Comment by rakshitmaini** [comment]
Small logical problem, issue resolved committed to master. 👍 
But still need to delete earlier created folder explicitly. 👎

**Comment by batrasudhanshu** [comment]
Previous folders has been deleted explicitly

**Comment by batrasudhanshu** [comment]
While deleting project, entry gets deleted from database as well as storage. Good to close the issue 👍
